modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/Gsjsjzhznsz/BotSentinel/issues"

[[mods]]
modId="botsentinel"
version="${file.jarVersion}"
displayName="BotSentinel"
description='''
无感风控反机器人 mod: 进服前拦截(QQ群零感知) + 特征库自动更新
+ 真人封禁网段追踪 + IP归属地拦截。
'''
authors="Gsjsjzhznsz"
displayURL="https://github.com/Gsjsjzhznsz/BotSentinel"

[[dependencies.botsentinel]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.botsentinel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="SERVER"
